import {
  getAllScenariosResponseSchema,
  objectTransactionSchema,
  scenarioSchema,
} from "@exopen/types";
import { z } from "zod";

z.array(
  z.object({ objectTransactions: z.array(objectTransactionSchema) })
).parse([
  {
    objectTransactions: [
      {
        id: "423821",
        amount: 600,
        quantity: 0,
        spread: 0,
        periodFrom: "2023-01-01",
        periodTo: "2023-06-01",
        refType: "account",
        savedScenarioId: "54634",
        allocationKey: null,
        generalObject: null,
        distribution: [],
        account: {
          id: 3813507,
          accountNumber: "3003",
          accountName: "Försäljning inom Sverige, 6 % moms",
          versionId: 3727,
          from_id: null,
        },
        per: "whole_period",
        customerDim: {
          id: "110276",
          name: "Saknar kund",
          code: "",
        },
        projectDim: {
          id: "110618",
          name: "Accountor - Krafthus via IXT",
          code: "2020952",
        },
        supplierDim: {
          id: "110700",
          name: "AB Stjärntryck i Stockholm",
          code: "585-2686",
        },
        productDim: {
          id: null,
          name: null,
          code: null,
        },
        costBearerDim: {
          id: null,
          name: null,
          code: null,
        },
      },
    ],
  },
]);

/*


 {
        id: "423823",
        amount: 0,
        quantity: 0,
        spread: 0,
        periodFrom: "2023-03-01",
        periodTo: "2023-05-01",
        refType: "sale_lts",
        savedScenarioId: "54634",
        allocationKey: null,
        generalObject: {
          id: "22894",
          name: "Produkt 2 20%",
          amount: 20000,
          planId: "3727",
          refType: "sale",
          accountRecipes: [
            {
              generalObjectId: 22894,
              id: "29216",
              name: "Fsg och inköp 20 marginal",
              description:
                "Ett enkelt exempel på ett kontorecept för försäljning och inköp med 20% marginal.",
              versionId: "3727",
              jsonRows: [
                {
                  id: 101424,
                  amount: 1,
                  parentId: null,
                  offsetDays: null,
                  accountRecipeId: 29216,
                  accountId: 3813006,
                  accountName: "Försäljning inom Sverige, 25 % moms",
                  accountNumber: "3001",
                  amountType: "percent",
                },
                {
                  id: 101425,
                  amount: 0.8,
                  parentId: null,
                  offsetDays: null,
                  accountRecipeId: 29216,
                  accountId: 3812875,
                  accountName: "Inköp av varor från Sverige",
                  accountNumber: "4000",
                  amountType: "percent",
                },
              ],
              moduleTag: "sale",
              createdAt: new Date("2023-02-07T13:40:05.079Z"),
            },
          ],
          createdAt: new Date("2023-02-07T13:40:05.079Z"),
          code: "b35a6f1c-cdba-492f-8e83-030640fe003a",
          active: false,
          syncStatus: null,
        },
        distribution: [
          {
            id: "423632",
            amount: 0.333333333333,
            objectTransactionId: "423823",
            organizationalUnit: {
              id: "63393",
              name: "Stockholm Gemensam",
              code: "1000",
              active: false,
              planId: "3727",
              createdAt: new Date("2023-02-07T13:40:05.079Z"),
              syncStatus: null,
            },
          },
          {
            id: "423633",
            amount: 0.333333333333,
            objectTransactionId: "423823",
            organizationalUnit: {
              id: "63403",
              name: "Säljchef",
              code: "1300",
              active: false,
              planId: "3727",
              createdAt: new Date("2023-02-07T13:40:05.079Z"),
              syncStatus: null,
            },
          },
          {
            id: "423634",
            amount: 0.333333333333,
            objectTransactionId: "423823",
            organizationalUnit: {
              id: "63401",
              name: "test",
              code: "0",
              active: false,
              planId: "3727",
              createdAt: new Date("2023-02-07T13:40:05.079Z"),
              syncStatus: null,
            },
          },
        ],
        account: null,
        per: "whole_period",
        customerDim: {
          id: null,
          name: null,
          code: null,
        },
        projectDim: {
          id: null,
          name: null,
          code: null,
        },
        supplierDim: {
          id: null,
          name: null,
          code: null,
        },
        productDim: {
          id: null,
          name: null,
          code: null,
        },
        costBearerDim: {
          id: null,
          name: null,
          code: null,
        },
      },
      {
        id: "422264",
        amount: 0,
        quantity: 45,
        spread: 0,
        periodFrom: "2023-01-01",
        periodTo: "2023-06-01",
        refType: "sale",
        savedScenarioId: "54634",
        allocationKey: null,
        generalObject: {
          id: "22894",
          name: "Produkt 2 20%",
          amount: 20000,
          planId: "3727",
          refType: "sale",
          accountRecipes: [
            {
              generalObjectId: 22894,
              id: "29216",
              name: "Fsg och inköp 20 marginal",
              description:
                "Ett enkelt exempel på ett kontorecept för försäljning och inköp med 20% marginal.",
              versionId: "3727",
              jsonRows: [
                {
                  id: 101424,
                  amount: 1,
                  parentId: null,
                  offsetDays: null,
                  accountRecipeId: 29216,
                  accountId: 3813006,
                  accountName: "Försäljning inom Sverige, 25 % moms",
                  accountNumber: "3001",
                  amountType: "percent",
                },
                {
                  id: 101425,
                  amount: 0.8,
                  parentId: null,
                  offsetDays: null,
                  accountRecipeId: 29216,
                  accountId: 3812875,
                  accountName: "Inköp av varor från Sverige",
                  accountNumber: "4000",
                  amountType: "percent",
                },
              ],
              moduleTag: "sale",
              createdAt: new Date("2023-02-07T13:40:05.079Z"),
            },
          ],
          createdAt: new Date("2023-02-07T13:40:05.079Z"),
          code: "b35a6f1c-cdba-492f-8e83-030640fe003a",
          active: false,
          syncStatus: null,
        },
        distribution: [
          {
            id: "422073",
            amount: 1,
            objectTransactionId: "422264",
            organizationalUnit: {
              id: "63420",
              name: "Saknar org.enhet",
              code: "",
              active: false,
              planId: "3727",
              createdAt: new Date("2023-02-07T13:40:05.079Z"),
              syncStatus: null,
            },
          },
        ],
        account: null,
        per: "whole_period",
        customerDim: {
          id: "110276",
          name: "Saknar kund",
          code: "",
        },
        projectDim: {
          id: "110647",
          name: "Saknar projekt",
          code: "",
        },
        supplierDim: {
          id: "111113",
          name: "Saknar leverantör",
          code: "",
        },
        productDim: {
          id: null,
          name: null,
          code: null,
        },
        costBearerDim: {
          id: null,
          name: null,
          code: null,
        },
      },
      {
        id: "423824",
        amount: 0,
        quantity: 0,
        spread: 0,
        periodFrom: "2023-03-01",
        periodTo: "2023-05-01",
        refType: "sale_lts",
        savedScenarioId: "54634",
        allocationKey: null,
        generalObject: {
          id: "22895",
          name: "Produkt 3 Fsg mot KF",
          amount: 10000,
          planId: "3727",
          refType: "sale",
          accountRecipes: [
            {
              generalObjectId: 22895,
              id: "29217",
              name: "Fsg mot KF",
              description:
                "Ett enkelt exempel på ett kontorecept för försäljning mot Kundfordringar.",
              versionId: "3727",
              jsonRows: [
                {
                  id: 101426,
                  amount: 1,
                  parentId: null,
                  offsetDays: null,
                  accountRecipeId: 29217,
                  accountId: 3813006,
                  accountName: "Försäljning inom Sverige, 25 % moms",
                  accountNumber: "3001",
                  amountType: "percent",
                },
                {
                  id: 101427,
                  amount: 0.25,
                  parentId: null,
                  offsetDays: null,
                  accountRecipeId: 29217,
                  accountId: 3812542,
                  accountName: "Utgående moms, 25 %",
                  accountNumber: "2610",
                  amountType: "percent",
                },
                {
                  id: 101428,
                  amount: 1.25,
                  parentId: null,
                  offsetDays: null,
                  accountRecipeId: 29217,
                  accountId: 3812726,
                  accountName: "Kundfordringar",
                  accountNumber: "1510",
                  amountType: "percent",
                },
                {
                  id: 101429,
                  amount: -1.25,
                  parentId: null,
                  offsetDays: 45,
                  accountRecipeId: 29217,
                  accountId: 3812726,
                  accountName: "Kundfordringar",
                  accountNumber: "1510",
                  amountType: "percent",
                },
                {
                  id: 101430,
                  amount: 1.25,
                  parentId: null,
                  offsetDays: 45,
                  accountRecipeId: 29217,
                  accountId: 3812798,
                  accountName: "Nordea",
                  accountNumber: "1930",
                  amountType: "percent",
                },
              ],
              moduleTag: "sale",
              createdAt: new Date("2023-02-07T13:40:05.079Z"),
            },
          ],
          createdAt: new Date("2023-02-07T13:40:05.079Z"),
          code: "dd363995-87e7-495f-bf06-ce50258d8587",
          active: false,
          syncStatus: null,
        },
        distribution: [
          {
            id: "423635",
            amount: 0.333333333333,
            objectTransactionId: "423824",
            organizationalUnit: {
              id: "63393",
              name: "Stockholm Gemensam",
              code: "1000",
              active: false,
              planId: "3727",
              createdAt: new Date("2023-02-07T13:40:05.079Z"),
              syncStatus: null,
            },
          },
          {
            id: "423636",
            amount: 0.333333333333,
            objectTransactionId: "423824",
            organizationalUnit: {
              id: "63403",
              name: "Säljchef",
              code: "1300",
              active: false,
              planId: "3727",
              createdAt: new Date("2023-02-07T13:40:05.079Z"),
              syncStatus: null,
            },
          },
          {
            id: "423637",
            amount: 0.333333333333,
            objectTransactionId: "423824",
            organizationalUnit: {
              id: "63401",
              name: "test",
              code: "0",
              active: false,
              planId: "3727",
              createdAt: new Date("2023-02-07T13:40:05.079Z"),
              syncStatus: null,
            },
          },
        ],
        account: null,
        per: "whole_period",
        customerDim: {
          id: null,
          name: null,
          code: null,
        },
        projectDim: {
          id: null,
          name: null,
          code: null,
        },
        supplierDim: {
          id: null,
          name: null,
          code: null,
        },
        productDim: {
          id: null,
          name: null,
          code: null,
        },
        costBearerDim: {
          id: null,
          name: null,
          code: null,
        },
      },
      {
        id: "423825",
        amount: 0,
        quantity: 167,
        spread: 0,
        periodFrom: "2023-01-01",
        periodTo: "2023-06-30",
        refType: "sale",
        savedScenarioId: "54634",
        allocationKey: {
          id: "673383",
          name: "Manual (423825)",
          keyType: "private",
          organizationalUnitId: null,
          objectTransaction: "423825",
          allocations: [
            {
              id: "6252901",
              period: "2023-02-01",
              amount: 0,
              allocationKeyId: "673383",
              generatedFor: null,
            },
            {
              id: "6252905",
              period: "2023-06-01",
              amount: 0,
              allocationKeyId: "673383",
              generatedFor: null,
            },
            {
              id: "6252900",
              period: "2023-01-01",
              amount: 0.413173652695,
              allocationKeyId: "673383",
              generatedFor: null,
            },
            {
              id: "6252904",
              period: "2023-05-01",
              amount: 0,
              allocationKeyId: "673383",
              generatedFor: null,
            },
            {
              id: "6252903",
              period: "2023-04-01",
              amount: 0.586826347305,
              allocationKeyId: "673383",
              generatedFor: null,
            },
            {
              id: "6252902",
              period: "2023-03-01",
              amount: 0,
              allocationKeyId: "673383",
              generatedFor: null,
            },
          ],
          createdAt: "2023-02-16T22:51:06.776193+00:00",
          accountId: null,
        },
        generalObject: {
          id: "22895",
          name: "Produkt 3 Fsg mot KF",
          amount: 10000,
          planId: "3727",
          refType: "sale",
          accountRecipes: [
            {
              generalObjectId: 22895,
              id: "29217",
              name: "Fsg mot KF",
              description:
                "Ett enkelt exempel på ett kontorecept för försäljning mot Kundfordringar.",
              versionId: "3727",
              jsonRows: [
                {
                  id: 101426,
                  amount: 1,
                  parentId: null,
                  offsetDays: null,
                  accountRecipeId: 29217,
                  accountId: 3813006,
                  accountName: "Försäljning inom Sverige, 25 % moms",
                  accountNumber: "3001",
                  amountType: "percent",
                },
                {
                  id: 101427,
                  amount: 0.25,
                  parentId: null,
                  offsetDays: null,
                  accountRecipeId: 29217,
                  accountId: 3812542,
                  accountName: "Utgående moms, 25 %",
                  accountNumber: "2610",
                  amountType: "percent",
                },
                {
                  id: 101428,
                  amount: 1.25,
                  parentId: null,
                  offsetDays: null,
                  accountRecipeId: 29217,
                  accountId: 3812726,
                  accountName: "Kundfordringar",
                  accountNumber: "1510",
                  amountType: "percent",
                },
                {
                  id: 101429,
                  amount: -1.25,
                  parentId: null,
                  offsetDays: 45,
                  accountRecipeId: 29217,
                  accountId: 3812726,
                  accountName: "Kundfordringar",
                  accountNumber: "1510",
                  amountType: "percent",
                },
                {
                  id: 101430,
                  amount: 1.25,
                  parentId: null,
                  offsetDays: 45,
                  accountRecipeId: 29217,
                  accountId: 3812798,
                  accountName: "Nordea",
                  accountNumber: "1930",
                  amountType: "percent",
                },
              ],
              moduleTag: "sale",
              createdAt: new Date("2023-02-07T13:40:05.079Z"),
            },
          ],
          createdAt: new Date("2023-02-07T13:40:05.079Z"),
          code: "dd363995-87e7-495f-bf06-ce50258d8587",
          active: false,
          syncStatus: null,
        },
        distribution: [
          {
            id: "423638",
            amount: 1,
            objectTransactionId: "423825",
            organizationalUnit: {
              id: "63409",
              name: "Sälj Syd",
              code: "2100",
              active: false,
              planId: "3727",
              createdAt: new Date("2023-02-07T13:40:05.079Z"),
              syncStatus: null,
            },
          },
        ],
        account: null,
        per: "whole_period",
        customerDim: {
          id: "110276",
          name: "Saknar kund",
          code: "",
        },
        projectDim: {
          id: "110647",
          name: "Saknar projekt",
          code: "",
        },
        supplierDim: {
          id: "111113",
          name: "Saknar leverantör",
          code: "",
        },
        productDim: {
          id: null,
          name: null,
          code: null,
        },
        costBearerDim: {
          id: null,
          name: null,
          code: null,
        },
      },


*/
